export const bookmarks = [
  {
    id: "b1",
    title: "React Documentation",
    url: "https://react.dev/",
    notes: "The official documentation for React.",
    tags: ["React", "JavaScript"],
    liked: false,
    saved: true,
    collectionId: "all",
  },
  {
    id: "b2",
    title: "Next.js Best Practices",
    url: "https://nextjs.org/docs/app/building-your-application/optimizing/best-practices",
    notes: "Learn how to build performant Next.js applications",
    tags: ["Next.js", "Web Development"],
    liked: true,
    saved: true,
    collectionId: "work",
  },
  {
    id: "b3",
    title: "TypeScript Advanced Types",
    url: "https://www.typescriptlang.org/docs/handbook/advanced-types.html",
    notes: "Master advanced TypeScript patterns",
    tags: ["TypeScript", "Programming"],
    liked: false,
    saved: false,
    collectionId: "all",
  },
];
